// <auto-generated />
using JavaJamCoffeeHouse.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace JavaJamCoffeeHouse.Migrations
{
    [DbContext(typeof(JavaJamCoffeeHouseContext))]
    [Migration("20180419170551_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JavaJamCoffeeHouse.Models.Jobs", b =>
                {
                    b.Property<int>("JobsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Experience");

                    b.Property<string>("Name");

                    b.HasKey("JobsId");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
